packages:
  - 'npm-package/codemirror-expression-editor'
  - 'npm-package/webpack-config-builder'
  - 'npm-package/stylelint-config'

publicHoistPattern:
  - 'stylelint**'
  - 'webpack**'
  - '**loader**'
  - 'glob'
  - 'minimist'

allowedDeprecatedVersions:
  eslint: '^8.57'
  popper.js: '^1.16'

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@oroinc/*"
